In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df = pd.read_csv('gurgaon_properties.csv')

In [3]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 36 Sohna,flat,signature global park 4,0.82,7585.0,1081.0,Super Built up area 1081(100.43 sq.m.)Carpet a...,3,2,2,not available,"144, Sector 36 Sohna, Gurgaon, Haryana",2.0,NaN,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'The Leaf Mall ...",We need to shift somewhere else,NaN,"['Lift(s)', 'Park']",NaN
1,2 BHK Flat in Sector 89 Gurgaon,flat,smart world gems,0.95,8600.0,1105.0,Carpet area: 1103 (102.47 sq.m.),2,2,2,"study room,servant room","O 118d, Sector 89 Gurgaon, Gurgaon, Haryana",4.0,NaN,Within 6 months,"['Sant Soordas Sihi Metro Station', 'Airia Mal...",Smartworld gem4 th floor new construction,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,2 BHK Flat in Sector 86 Gurgaon,flat,pyramid elite,0.46,79.0,58228.0,Carpet area: 58141 (5401.48 sq.m.),2,2,1,not available,"Sector 86 Gurgaon, Gurgaon, Haryana",0.0,NaN,Under Construction,"['V3S Sapphire Ninety Mall', 'Sector 86 Road',...",Near to dwarka expressway\r\nNear to airport,[],"['Intercom Facility', 'Lift(s)', 'Park']","['Environment5 out of 5', 'Safety4.5 out of 5'..."
3,2 BHK Flat in Sohna,flat,breez global hill view,0.32,5470.0,585.0,Built Up area: 1000 (92.9 sq.m.)Carpet area: 5...,2,2,1,not available,"1701 & 1708, Sohna, Gurgaon, Haryana",17.0,NaN,0 to 1 Year Old,"['Huda City Centre', 'Omaxe City Centre', 'Nin...",Both adjacent properties available which can b...,[],"['Feng Shui / Vaastu Compliant', 'Security / F...","['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
4,3 BHK Flat in Sector 92 Gurgaon,flat,bestech park view sanskruti,1.60,8020.0,1995.0,Super Built up area 1995(185.34 sq.m.)Built Up...,3,4,3+,"servant room,others","Sector 92 Gurgaon, Gurgaon, Haryana",10.0,North-West,1 to 5 Year Old,"['Sapphire 93 Mall', 'Dwarka Expressway', 'NH-...",Check out this 3 bhk apartment for sale in bes...,"['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '3 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."

In [4]:
df.isna().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [5]:
df.insert(loc=3,column='sector',value =  df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [11]:
a= df['sector'].value_counts()[df['sector'].value_counts() >3]

In [21]:
df['sector'].isna().sum()

0

In [23]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [25]:
df

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 36 Sohna,flat,signature global park 4,Sector 36 Sohna,0.82,7585.0,1081.0,Super Built up area 1081(100.43 sq.m.)Carpet a...,3,2,...,not available,"144, Sector 36 Sohna, Gurgaon, Haryana",2.0,NaN,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'The Leaf Mall ...",We need to shift somewhere else,NaN,"['Lift(s)', 'Park']",NaN
1,2 BHK Flat in Sector 89 Gurgaon,flat,smart world gems,Sector 89,0.95,8600.0,1105.0,Carpet area: 1103 (102.47 sq.m.),2,2,...,"study room,servant room","O 118d, Sector 89 Gurgaon, Gurgaon, Haryana",4.0,NaN,Within 6 months,"['Sant Soordas Sihi Metro Station', 'Airia Mal...",Smartworld gem4 th floor new construction,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,2 BHK Flat in Sector 86 Gurgaon,flat,pyramid elite,Sector 86,0.46,79.0,58228.0,Carpet area: 58141 (5401.48 sq.m.),2,2,...,not available,"Sector 86 Gurgaon, Gurgaon, Haryana",0.0,NaN,Under Construction,"['V3S Sapphire Ninety Mall', 'Sector 86 Road',...",Near to dwarka expressway\r\nNear to airport,[],"['Intercom Facility', 'Lift(s)', 'Park']","['Environment5 out of 5', 'Safety4.5 out of 5'..."
3,2 BHK Flat in Sohna,flat,breez global hill view,Sohna,0.32,5470.0,585.0,Built Up area: 1000 (92.9 sq.m.)Carpet area: 5...,2,2,...,not available,"1701 & 1708, Sohna, Gurgaon, Haryana",17.0,NaN,0 to 1 Year Old,"['Huda City Centre', 'Omaxe City Centre', 'Nin...",Both adjacent properties available which can b...,[],"['Feng Shui / Vaastu Compliant', 'Security / F...","['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
4,3 BHK Flat in Sector 92 Gurgaon,flat,bestech park view sanskruti,Sector 92,1.60,8020.0,1995.0,Super Built up area 1995(185.34 sq.m.)Built Up...,3,4,...,"servant room,others","Sector 92 Gurgaon, Gurgaon, Haryana",10.0,North-West,1 to 5 Year Old,"['Sapphire 93 Mall', 'Dwarka Expressway', 'NH-...",Check out this 3 bhk apartment for sale in bes...,"['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '3 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3955,2 BHK Flat in Sector 84 Gurgaon,flat,pivotal devaan,Sector 84,0.37,6346.0,583.0,Super Built up area 583(54.16 sq.m.)Carpet are...,2,2,...,not available,"Sector 84 Gurgaon, Gurgaon, Haryana",5.0,North-West,1 to 5 Year Old,"['Dwarka Expressway', 'RPS International Schoo...","Its 2bhk, semi furnished flat, middle floor, p...",[],"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3956,5 Bedroom House for sale in Sector 109 Gurgaon,house,international city by sobha phase 1,Sector 109,6.00,9634.0,6228.0,Plot area 692(578.6 sq.m.),5,5,...,"pooja room,study room,servant room,store room","040, Sector 109 Gurgaon, Gurgaon, Haryana",2.0,South-West,1 to 5 Year Old,"['Dwarka sector 21 metro station', 'Pacific D2...",Duplex villasDuplex villas at sobha internatio...,NaN,"['Water purifier', 'Centrally Air Conditioned'...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
3957,1 BHK Flat in Sector 2 Gurgaon,flat,ansal api celebrity suites,Sector 2,0.60,8163.0,735.0,Super Built up area 735(68.28 sq.m.),1,1,...,not available,"Sector 2 Gurgaon, Gurgaon, Haryana",5.0,North-East,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Looking for a 1 bhk property for sale in gurga...,"['1 Wardrobe', '2 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Intercom Facility', 'Lift(s...",NaN
3958,5 Bedroom House for sale in B Block Sushant Lo...,house,independent,B Block Sushant Lok Phase 1,15.50,28233.0,5490.0,Plot area 610(510.04 sq.m.),5,6,...,"pooja room,study room,servant room,store room","B Block Sushant Lok Phase 1, Gurgaon, Haryana",3.0,East,5 to 10 Year Old,"['Iffco chowk metro station', 'Huda city centr...","Basement , ground floor, first floor and terra...",[],"['Private Garden / Terrace', 'Water purifier',...","['Environment4 out of 5', 'Lifestyle4.5 out of..."
3960,3 BHK Flat in Sector 68 Gurgaon,flat,m3m ikonic,Sector 68,1.78,9128.0,1950.0,Super Built up area 1950(181.16 sq.m.)Built Up...,3,3,...,not available,"T-5, Sector 68 Gurgaon, Gurgaon, Haryana",27.0,South,1 to 5 Year Old,"['Airia Mall', 'Sohna Road', 'Vidyamrat Public...","M3m ikonic in sector 68, gurgaon is a ready-To...","['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [ ]:
df.fillna