In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df = pd.read_excel('flats.xlsx')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3027 entries, 0 to 3026
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3027 non-null   object
 1   link             3027 non-null   object
 2   society          3026 non-null   object
 3   price            3007 non-null   object
 4   area             3014 non-null   object
 5   areaWithType     3008 non-null   object
 6   bedRoom          3008 non-null   object
 7   bathroom         3008 non-null   object
 8   balcony          3008 non-null   object
 9   additionalRoom   1694 non-null   object
 10  address          3002 non-null   object
 11  floorNum         3006 non-null   object
 12  facing           2127 non-null   object
 13  agePossession    3007 non-null   object
 14  nearbyLocations  2913 non-null   object
 15  description      3008 non-null   object
 16  furnishDetails   2203 non-null   object
 17  features         2594 non-null   object
 18  rating           2676 non-null   object
 19  property_id      3008 non-null   object
dtypes: object(20)
memory usage: 473.1+ KB

In [4]:
df.shape

(3027, 20)

In [5]:
df.isna().sum()

property_name         0
link                  0
society               1
price                20
area                 13
areaWithType         19
bedRoom              19
bathroom             19
balcony              19
additionalRoom     1333
address              25
floorNum             21
facing              900
agePossession        20
nearbyLocations     114
description          19
furnishDetails      824
features            433
rating              351
property_id          19
dtype: int64

In [6]:
df[df.isna()].shape

(3027, 20)

In [7]:
df.duplicated().sum()

0

In [8]:
df.drop(columns=['link','property_id'],inplace=True)

In [9]:
df

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 85 Gurgaon,Godrej Air,2.5 Crore,"₹ 1,379/sq.ft.",Carpet area: 18122 (1683.59 sq.m.),4 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Others","1601-A 2, Sector 85 Gurgaon, Gurgaon, Haryana",16th of 24 Floors,North-East,2024-03-01 00:00:00,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...",Godrej as a brand and very few densed society,"['4 Wardrobe', '1 Water Purifier', '4 Fan', '1...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1,3 BHK Flat in Sector 88A Gurgaon,Godrej Icon,1.75 Crore,"₹ 1,384/sq.ft.",Carpet area: 1175.11,3 Bedrooms,3 Bathrooms,3+ Balconies,NaN,"Sector 88A Gurgaon, Gurgaon, Haryana",6th of 10 Floors,NaN,0 to 1 Year Old,"['JMS Crosswalk', ""Saint Paul's School"", 'Indu...",Godrej icon is one of the most popular destina...,[],NaN,NaN
2,3 BHK Flat in Malibu Town,Malibu Towne,2.4 Crore,"₹ 10,000/sq.ft.",Carpet area: 2400 (222.97 sq.m.),3 Bedrooms,3 Bathrooms,No Balcony,NaN,"Malibu Town, Gurgaon, Haryana",Ground of 3 Floors,West,5 to 10 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",Residential apartment for sell.The property co...,"['1 Water Purifier', '3 Fan', '1 Exhaust Fan',...","['Maintenance Staff', 'Swimming Pool', 'Park']","['Environment5 out of 5', 'Safety5 out of 5', ..."
3,2 BHK Flat in Sector 79 Gurgaon,M3M Golfestate,1.4 Crore,"₹ 10,000/sq.ft.",Carpet area: 1400 (130.06 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,"Study Room,Servant Room,Store Room","Sector 79 Gurgaon, Gurgaon, Haryana",4th of 40 Floors,East,NaN,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","Individual bar plus ground floor room , two si...","['1 Water Purifier', '1 Fan', '1 Fridge', '1 D...","['Intercom Facility', 'Lift(s)', 'High Ceiling...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,3 BHK Flat in Sector 30 Gurgaon,AFNHB Jalvayu Vihar3.7 ★,1.3 Crore,"₹ 10,000/sq.ft.",Super Built up area 1500(139.35 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Sector 30 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,North-East,10+ Year Old,"['Huda city centre metro station', 'Axis bank ...",Property is fully renovated with all extention...,[],"['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Green Area4.5 out of 5', 'Construction4 out ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3022,2 BHK Flat in Sector 95A Gurgaon,The Roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
3023,2 BHK Flat in Sector 107 Gurgaon,Signature Global Solera3.7 ★,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3024,3 BHK Flat in Sector 104 Gurgaon,Godrej Summit3.7 ★,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
3025,4 BHK Flat in Gwal Pahari,Krrish Provence Estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
3026,4 BHK Flat in Sector 95 Gurgaon,Sidhartha NCR One Phase 24.1 ★,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [10]:
df.rename(columns={'area':'price per sq feet'},inplace=True)

In [11]:
df

,property_name,society,price,price per sq feet,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 85 Gurgaon,Godrej Air,2.5 Crore,"₹ 1,379/sq.ft.",Carpet area: 18122 (1683.59 sq.m.),4 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Others","1601-A 2, Sector 85 Gurgaon, Gurgaon, Haryana",16th of 24 Floors,North-East,2024-03-01 00:00:00,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...",Godrej as a brand and very few densed society,"['4 Wardrobe', '1 Water Purifier', '4 Fan', '1...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1,3 BHK Flat in Sector 88A Gurgaon,Godrej Icon,1.75 Crore,"₹ 1,384/sq.ft.",Carpet area: 1175.11,3 Bedrooms,3 Bathrooms,3+ Balconies,NaN,"Sector 88A Gurgaon, Gurgaon, Haryana",6th of 10 Floors,NaN,0 to 1 Year Old,"['JMS Crosswalk', ""Saint Paul's School"", 'Indu...",Godrej icon is one of the most popular destina...,[],NaN,NaN
2,3 BHK Flat in Malibu Town,Malibu Towne,2.4 Crore,"₹ 10,000/sq.ft.",Carpet area: 2400 (222.97 sq.m.),3 Bedrooms,3 Bathrooms,No Balcony,NaN,"Malibu Town, Gurgaon, Haryana",Ground of 3 Floors,West,5 to 10 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",Residential apartment for sell.The property co...,"['1 Water Purifier', '3 Fan', '1 Exhaust Fan',...","['Maintenance Staff', 'Swimming Pool', 'Park']","['Environment5 out of 5', 'Safety5 out of 5', ..."
3,2 BHK Flat in Sector 79 Gurgaon,M3M Golfestate,1.4 Crore,"₹ 10,000/sq.ft.",Carpet area: 1400 (130.06 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,"Study Room,Servant Room,Store Room","Sector 79 Gurgaon, Gurgaon, Haryana",4th of 40 Floors,East,NaN,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","Individual bar plus ground floor room , two si...","['1 Water Purifier', '1 Fan', '1 Fridge', '1 D...","['Intercom Facility', 'Lift(s)', 'High Ceiling...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,3 BHK Flat in Sector 30 Gurgaon,AFNHB Jalvayu Vihar3.7 ★,1.3 Crore,"₹ 10,000/sq.ft.",Super Built up area 1500(139.35 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Sector 30 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,North-East,10+ Year Old,"['Huda city centre metro station', 'Axis bank ...",Property is fully renovated with all extention...,[],"['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Green Area4.5 out of 5', 'Construction4 out ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3022,2 BHK Flat in Sector 95A Gurgaon,The Roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
3023,2 BHK Flat in Sector 107 Gurgaon,Signature Global Solera3.7 ★,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3024,3 BHK Flat in Sector 104 Gurgaon,Godrej Summit3.7 ★,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
3025,4 BHK Flat in Gwal Pahari,Krrish Provence Estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
3026,4 BHK Flat in Sector 95 Gurgaon,Sidhartha NCR One Phase 24.1 ★,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [12]:
df['society'].value_counts()

society
SS The Leaf3.8 ★                             73
Tulip Violet4.3 ★                            40
Shapoorji Pallonji Joyville Gurugram4.0 ★    39
Signature Global Park4.0 ★                   36
Shree Vardhman Victoria3.8 ★                 35
                                             ..
Emaar Emerald Hills4.1 ★                      1
Mvn athens sohna gurgaon                      1
Senate Court                                  1
Breez Global Heights                          1
Sidhartha NCR One Phase 24.1 ★                1
Name: count, Length: 638, dtype: int64

In [13]:
def remove_1(text):
    return re.sub(r"\d+(\.\d+)?\s?★", "", str(text).strip().lower())

In [14]:
df['society'] = df['society'].apply(remove_1)

In [15]:
df['society'].value_counts().shape

(608,)

In [16]:
df['society'].value_counts()

society
tulip violet                            75
ss the leaf                             74
shapoorji pallonji joyville gurugram    45
signature global park                   36
shree vardhman victoria                 35
                                        ..
sbr minda sec 1 imt manesar              1
vidya apartment                          1
sbr minda sec-1 imt manesar              1
raheja vedas                             1
the millennia 2                          1
Name: count, Length: 608, dtype: int64

In [17]:
df.head()

,property_name,society,price,price per sq feet,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 85 Gurgaon,godrej air,2.5 Crore,"₹ 1,379/sq.ft.",Carpet area: 18122 (1683.59 sq.m.),4 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Others","1601-A 2, Sector 85 Gurgaon, Gurgaon, Haryana",16th of 24 Floors,North-East,2024-03-01 00:00:00,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...",Godrej as a brand and very few densed society,"['4 Wardrobe', '1 Water Purifier', '4 Fan', '1...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1,3 BHK Flat in Sector 88A Gurgaon,godrej icon,1.75 Crore,"₹ 1,384/sq.ft.",Carpet area: 1175.11,3 Bedrooms,3 Bathrooms,3+ Balconies,NaN,"Sector 88A Gurgaon, Gurgaon, Haryana",6th of 10 Floors,NaN,0 to 1 Year Old,"['JMS Crosswalk', ""Saint Paul's School"", 'Indu...",Godrej icon is one of the most popular destina...,[],NaN,NaN
2,3 BHK Flat in Malibu Town,malibu towne,2.4 Crore,"₹ 10,000/sq.ft.",Carpet area: 2400 (222.97 sq.m.),3 Bedrooms,3 Bathrooms,No Balcony,NaN,"Malibu Town, Gurgaon, Haryana",Ground of 3 Floors,West,5 to 10 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",Residential apartment for sell.The property co...,"['1 Water Purifier', '3 Fan', '1 Exhaust Fan',...","['Maintenance Staff', 'Swimming Pool', 'Park']","['Environment5 out of 5', 'Safety5 out of 5', ..."
3,2 BHK Flat in Sector 79 Gurgaon,m3m golfestate,1.4 Crore,"₹ 10,000/sq.ft.",Carpet area: 1400 (130.06 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,"Study Room,Servant Room,Store Room","Sector 79 Gurgaon, Gurgaon, Haryana",4th of 40 Floors,East,NaN,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","Individual bar plus ground floor room , two si...","['1 Water Purifier', '1 Fan', '1 Fridge', '1 D...","['Intercom Facility', 'Lift(s)', 'High Ceiling...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,3 BHK Flat in Sector 30 Gurgaon,afnhb jalvayu vihar,1.3 Crore,"₹ 10,000/sq.ft.",Super Built up area 1500(139.35 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Sector 30 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,North-East,10+ Year Old,"['Huda city centre metro station', 'Axis bank ...",Property is fully renovated with all extention...,[],"['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Green Area4.5 out of 5', 'Construction4 out ..."

In [18]:
df['price'].isna().sum()

20

In [19]:
def re_price(price):
    price = str(price).lower().strip()
    if "crore" in price:
        amt = float(re.sub(r"[^\d.]", "", price))
        return round(amt, 2)
    elif 'lac' in price:
        amt = float(re.sub(r"[^\d.]", "", price))
        return  round(amt/100, 2)
    else:
        return "Not Avaliable"

In [20]:
df['price'] = df['price'].apply(re_price)

In [21]:
import re

def extract_number(text):
    # Remove commas and then extract the numeric part
    text = str(text).replace(",", "")  # Remove commas
    numbers = re.findall(r'\d+', text)  # Extract digits
    if numbers:
        return int(numbers[0])  # Convert to integer
    return None  # Return None if no number is found

In [22]:
df['price per sq feet'] = df['price per sq feet'].apply(extract_number)

In [23]:
df = df[~df['bedRoom'].isna()]

In [24]:
df

,property_name,society,price,price per sq feet,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 85 Gurgaon,godrej air,2.5,1379.0,Carpet area: 18122 (1683.59 sq.m.),4 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Others","1601-A 2, Sector 85 Gurgaon, Gurgaon, Haryana",16th of 24 Floors,North-East,2024-03-01 00:00:00,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...",Godrej as a brand and very few densed society,"['4 Wardrobe', '1 Water Purifier', '4 Fan', '1...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1,3 BHK Flat in Sector 88A Gurgaon,godrej icon,1.75,1384.0,Carpet area: 1175.11,3 Bedrooms,3 Bathrooms,3+ Balconies,NaN,"Sector 88A Gurgaon, Gurgaon, Haryana",6th of 10 Floors,NaN,0 to 1 Year Old,"['JMS Crosswalk', ""Saint Paul's School"", 'Indu...",Godrej icon is one of the most popular destina...,[],NaN,NaN
2,3 BHK Flat in Malibu Town,malibu towne,2.4,10000.0,Carpet area: 2400 (222.97 sq.m.),3 Bedrooms,3 Bathrooms,No Balcony,NaN,"Malibu Town, Gurgaon, Haryana",Ground of 3 Floors,West,5 to 10 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",Residential apartment for sell.The property co...,"['1 Water Purifier', '3 Fan', '1 Exhaust Fan',...","['Maintenance Staff', 'Swimming Pool', 'Park']","['Environment5 out of 5', 'Safety5 out of 5', ..."
3,2 BHK Flat in Sector 79 Gurgaon,m3m golfestate,1.4,10000.0,Carpet area: 1400 (130.06 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,"Study Room,Servant Room,Store Room","Sector 79 Gurgaon, Gurgaon, Haryana",4th of 40 Floors,East,NaN,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","Individual bar plus ground floor room , two si...","['1 Water Purifier', '1 Fan', '1 Fridge', '1 D...","['Intercom Facility', 'Lift(s)', 'High Ceiling...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,3 BHK Flat in Sector 30 Gurgaon,afnhb jalvayu vihar,1.3,10000.0,Super Built up area 1500(139.35 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Sector 30 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,North-East,10+ Year Old,"['Huda city centre metro station', 'Axis bank ...",Property is fully renovated with all extention...,[],"['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Green Area4.5 out of 5', 'Construction4 out ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3021,3 BHK Flat in Sector-2 Sohna,supertech hilltown,Not Avaliable,NaN,Built Up area: 1720 (159.79 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4th of 4 Floors,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN
3022,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Not Avaliable,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
3024,3 BHK Flat in Sector 104 Gurgaon,godrej summit,Not Avaliable,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
3025,4 BHK Flat in Gwal Pahari,krrish provence estate,Not Avaliable,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
3026,4 BHK Flat in Sector 95 Gurgaon,sidhartha ncr one phase,Not Avaliable,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [25]:
df['balcony'].value_counts()

balcony
3 Balconies     977
3+ Balconies    863
2 Balconies     751
1 Balcony       318
No Balcony       99
Name: count, dtype: int64

In [26]:
df['bedRoom'] =  df['bedRoom'].str.split(' ').str.get(0)

C:\Users\rkcas\AppData\Local\Temp\ipykernel_16188\3351959224.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['bedRoom'] =  df['bedRoom'].str.split(' ').str.get(0)

In [27]:
df['bathroom'] =  df['bathroom'].str.split(' ').str.get(0)

C:\Users\rkcas\AppData\Local\Temp\ipykernel_16188\1895272514.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['bathroom'] =  df['bathroom'].str.split(' ').str.get(0)

In [28]:
df

,property_name,society,price,price per sq feet,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 85 Gurgaon,godrej air,2.5,1379.0,Carpet area: 18122 (1683.59 sq.m.),4,5,3+ Balconies,"Pooja Room,Study Room,Others","1601-A 2, Sector 85 Gurgaon, Gurgaon, Haryana",16th of 24 Floors,North-East,2024-03-01 00:00:00,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...",Godrej as a brand and very few densed society,"['4 Wardrobe', '1 Water Purifier', '4 Fan', '1...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1,3 BHK Flat in Sector 88A Gurgaon,godrej icon,1.75,1384.0,Carpet area: 1175.11,3,3,3+ Balconies,NaN,"Sector 88A Gurgaon, Gurgaon, Haryana",6th of 10 Floors,NaN,0 to 1 Year Old,"['JMS Crosswalk', ""Saint Paul's School"", 'Indu...",Godrej icon is one of the most popular destina...,[],NaN,NaN
2,3 BHK Flat in Malibu Town,malibu towne,2.4,10000.0,Carpet area: 2400 (222.97 sq.m.),3,3,No Balcony,NaN,"Malibu Town, Gurgaon, Haryana",Ground of 3 Floors,West,5 to 10 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",Residential apartment for sell.The property co...,"['1 Water Purifier', '3 Fan', '1 Exhaust Fan',...","['Maintenance Staff', 'Swimming Pool', 'Park']","['Environment5 out of 5', 'Safety5 out of 5', ..."
3,2 BHK Flat in Sector 79 Gurgaon,m3m golfestate,1.4,10000.0,Carpet area: 1400 (130.06 sq.m.),2,2,2 Balconies,"Study Room,Servant Room,Store Room","Sector 79 Gurgaon, Gurgaon, Haryana",4th of 40 Floors,East,NaN,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","Individual bar plus ground floor room , two si...","['1 Water Purifier', '1 Fan', '1 Fridge', '1 D...","['Intercom Facility', 'Lift(s)', 'High Ceiling...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,3 BHK Flat in Sector 30 Gurgaon,afnhb jalvayu vihar,1.3,10000.0,Super Built up area 1500(139.35 sq.m.)Carpet a...,3,3,2 Balconies,NaN,"Sector 30 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,North-East,10+ Year Old,"['Huda city centre metro station', 'Axis bank ...",Property is fully renovated with all extention...,[],"['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Green Area4.5 out of 5', 'Construction4 out ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3021,3 BHK Flat in Sector-2 Sohna,supertech hilltown,Not Avaliable,NaN,Built Up area: 1720 (159.79 sq.m.),3,3,3 Balconies,NaN,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4th of 4 Floors,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN
3022,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Not Avaliable,NaN,Carpet area: 593 (55.09 sq.m.),2,2,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
3024,3 BHK Flat in Sector 104 Gurgaon,godrej summit,Not Avaliable,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3,3,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
3025,4 BHK Flat in Gwal Pahari,krrish provence estate,Not Avaliable,NaN,Built Up area: 5800 (538.84 sq.m.),4,5,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
3026,4 BHK Flat in Sector 95 Gurgaon,sidhartha ncr one phase,Not Avaliable,NaN,Super Built up area 2354(218.69 sq.m.),4,4,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [29]:
df['balcony'].value_counts()

balcony
3 Balconies     977
3+ Balconies    863
2 Balconies     751
1 Balcony       318
No Balcony       99
Name: count, dtype: int64

In [30]:
df['balcony'] =  df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

C:\Users\rkcas\AppData\Local\Temp\ipykernel_16188\3749200033.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balcony'] =  df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

In [31]:
df.head()

,property_name,society,price,price per sq feet,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 85 Gurgaon,godrej air,2.5,1379.0,Carpet area: 18122 (1683.59 sq.m.),4,5,3+,"Pooja Room,Study Room,Others","1601-A 2, Sector 85 Gurgaon, Gurgaon, Haryana",16th of 24 Floors,North-East,2024-03-01 00:00:00,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...",Godrej as a brand and very few densed society,"['4 Wardrobe', '1 Water Purifier', '4 Fan', '1...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1,3 BHK Flat in Sector 88A Gurgaon,godrej icon,1.75,1384.0,Carpet area: 1175.11,3,3,3+,NaN,"Sector 88A Gurgaon, Gurgaon, Haryana",6th of 10 Floors,NaN,0 to 1 Year Old,"['JMS Crosswalk', ""Saint Paul's School"", 'Indu...",Godrej icon is one of the most popular destina...,[],NaN,NaN
2,3 BHK Flat in Malibu Town,malibu towne,2.4,10000.0,Carpet area: 2400 (222.97 sq.m.),3,3,0,NaN,"Malibu Town, Gurgaon, Haryana",Ground of 3 Floors,West,5 to 10 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",Residential apartment for sell.The property co...,"['1 Water Purifier', '3 Fan', '1 Exhaust Fan',...","['Maintenance Staff', 'Swimming Pool', 'Park']","['Environment5 out of 5', 'Safety5 out of 5', ..."
3,2 BHK Flat in Sector 79 Gurgaon,m3m golfestate,1.4,10000.0,Carpet area: 1400 (130.06 sq.m.),2,2,2,"Study Room,Servant Room,Store Room","Sector 79 Gurgaon, Gurgaon, Haryana",4th of 40 Floors,East,NaN,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","Individual bar plus ground floor room , two si...","['1 Water Purifier', '1 Fan', '1 Fridge', '1 D...","['Intercom Facility', 'Lift(s)', 'High Ceiling...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,3 BHK Flat in Sector 30 Gurgaon,afnhb jalvayu vihar,1.3,10000.0,Super Built up area 1500(139.35 sq.m.)Carpet a...,3,3,2,NaN,"Sector 30 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,North-East,10+ Year Old,"['Huda city centre metro station', 'Axis bank ...",Property is fully renovated with all extention...,[],"['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Green Area4.5 out of 5', 'Construction4 out ..."

In [32]:
# additionalRoom
df['additionalRoom'].value_counts().shape

(49,)

In [33]:
# additionalRoom
df[df['additionalRoom'].isna()]['additionalRoom'] = 'Not available'

C:\Users\rkcas\AppData\Local\Temp\ipykernel_16188\2087854841.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df['additionalRoom'].isna()]['additionalRoom'] = 'Not available'

In [34]:

df['additionalRoom'].fillna('not_avaliable',inplace=True)

C:\Users\rkcas\AppData\Local\Temp\ipykernel_16188\944514474.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('not_avaliable',inplace=True)
C:\Users\rkcas\AppData\Local\Temp\ipykernel_16188\944514474.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['additionalRoom'].fillna('not_avaliable',inplace=True)

In [35]:
df['additionalRoom'].isna().sum()

0

In [36]:
df['floorNum'] =  df['floorNum'].str.split(' ').str.get(0).str.replace('Ground','0').str.replace('Lower','0').str.replace('Basement','-1').str.extract(r'(\d+)')

C:\Users\rkcas\AppData\Local\Temp\ipykernel_16188\380581118.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['floorNum'] =  df['floorNum'].str.split(' ').str.get(0).str.replace('Ground','0').str.replace('Lower','0').str.replace('Basement','-1').str.extract(r'(\d+)')

In [37]:
df

,property_name,society,price,price per sq feet,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 85 Gurgaon,godrej air,2.5,1379.0,Carpet area: 18122 (1683.59 sq.m.),4,5,3+,"Pooja Room,Study Room,Others","1601-A 2, Sector 85 Gurgaon, Gurgaon, Haryana",16,North-East,2024-03-01 00:00:00,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...",Godrej as a brand and very few densed society,"['4 Wardrobe', '1 Water Purifier', '4 Fan', '1...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1,3 BHK Flat in Sector 88A Gurgaon,godrej icon,1.75,1384.0,Carpet area: 1175.11,3,3,3+,not_avaliable,"Sector 88A Gurgaon, Gurgaon, Haryana",6,NaN,0 to 1 Year Old,"['JMS Crosswalk', ""Saint Paul's School"", 'Indu...",Godrej icon is one of the most popular destina...,[],NaN,NaN
2,3 BHK Flat in Malibu Town,malibu towne,2.4,10000.0,Carpet area: 2400 (222.97 sq.m.),3,3,0,not_avaliable,"Malibu Town, Gurgaon, Haryana",0,West,5 to 10 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",Residential apartment for sell.The property co...,"['1 Water Purifier', '3 Fan', '1 Exhaust Fan',...","['Maintenance Staff', 'Swimming Pool', 'Park']","['Environment5 out of 5', 'Safety5 out of 5', ..."
3,2 BHK Flat in Sector 79 Gurgaon,m3m golfestate,1.4,10000.0,Carpet area: 1400 (130.06 sq.m.),2,2,2,"Study Room,Servant Room,Store Room","Sector 79 Gurgaon, Gurgaon, Haryana",4,East,NaN,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","Individual bar plus ground floor room , two si...","['1 Water Purifier', '1 Fan', '1 Fridge', '1 D...","['Intercom Facility', 'Lift(s)', 'High Ceiling...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,3 BHK Flat in Sector 30 Gurgaon,afnhb jalvayu vihar,1.3,10000.0,Super Built up area 1500(139.35 sq.m.)Carpet a...,3,3,2,not_avaliable,"Sector 30 Gurgaon, Gurgaon, Haryana",2,North-East,10+ Year Old,"['Huda city centre metro station', 'Axis bank ...",Property is fully renovated with all extention...,[],"['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Green Area4.5 out of 5', 'Construction4 out ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3021,3 BHK Flat in Sector-2 Sohna,supertech hilltown,Not Avaliable,NaN,Built Up area: 1720 (159.79 sq.m.),3,3,3,not_avaliable,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN
3022,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Not Avaliable,NaN,Carpet area: 593 (55.09 sq.m.),2,2,2,not_avaliable,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
3024,3 BHK Flat in Sector 104 Gurgaon,godrej summit,Not Avaliable,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3,3,3,not_avaliable,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
3025,4 BHK Flat in Gwal Pahari,krrish provence estate,Not Avaliable,NaN,Built Up area: 5800 (538.84 sq.m.),4,5,1,not_avaliable,"Gwal Pahari, Gurgaon, Haryana",17,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
3026,4 BHK Flat in Sector 95 Gurgaon,sidhartha ncr one phase,Not Avaliable,NaN,Super Built up area 2354(218.69 sq.m.),4,4,3+,not_avaliable,"Sector 95 Gurgaon, Gurgaon, Haryana",0,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [38]:
df['facing'].fillna('NA',inplace=True)

C:\Users\rkcas\AppData\Local\Temp\ipykernel_16188\3692945726.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA',inplace=True)
C:\Users\rkcas\AppData\Local\Temp\ipykernel_16188\3692945726.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['facing'].fillna('NA',inplace=True)

In [39]:
df['area'] = df['price']*10000000/df['price per sq feet']

C:\Users\rkcas\AppData\Local\Temp\ipykernel_16188\4197497508.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['area'] = df['price']*10000000/df['price per sq feet']

In [40]:
df['area']

0       18129.079043
1       12644.508671
2             2400.0
3             1400.0
4             1300.0
            ...
3021             NaN
3022             NaN
3024             NaN
3025             NaN
3026             NaN
Name: area, Length: 3008, dtype: object

In [41]:
df.insert(loc=4,column='area1',value=round((df['price']*10000000/df['price per sq feet'])))

In [42]:
df.insert(loc=1,column='property_type',value='flat')

In [43]:
df

,property_name,property_type,society,price,price per sq feet,area1,areaWithType,bedRoom,bathroom,balcony,...,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,area
0,4 BHK Flat in Sector 85 Gurgaon,flat,godrej air,2.5,1379.0,18129.079043,Carpet area: 18122 (1683.59 sq.m.),4,5,3+,...,"1601-A 2, Sector 85 Gurgaon, Gurgaon, Haryana",16,North-East,2024-03-01 00:00:00,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...",Godrej as a brand and very few densed society,"['4 Wardrobe', '1 Water Purifier', '4 Fan', '1...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment5 out of 5', 'Lifestyle5 out of 5...",18129.079043
1,3 BHK Flat in Sector 88A Gurgaon,flat,godrej icon,1.75,1384.0,12644.508671,Carpet area: 1175.11,3,3,3+,...,"Sector 88A Gurgaon, Gurgaon, Haryana",6,NA,0 to 1 Year Old,"['JMS Crosswalk', ""Saint Paul's School"", 'Indu...",Godrej icon is one of the most popular destina...,[],NaN,NaN,12644.508671
2,3 BHK Flat in Malibu Town,flat,malibu towne,2.4,10000.0,2400.0,Carpet area: 2400 (222.97 sq.m.),3,3,0,...,"Malibu Town, Gurgaon, Haryana",0,West,5 to 10 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",Residential apartment for sell.The property co...,"['1 Water Purifier', '3 Fan', '1 Exhaust Fan',...","['Maintenance Staff', 'Swimming Pool', 'Park']","['Environment5 out of 5', 'Safety5 out of 5', ...",2400.0
3,2 BHK Flat in Sector 79 Gurgaon,flat,m3m golfestate,1.4,10000.0,1400.0,Carpet area: 1400 (130.06 sq.m.),2,2,2,...,"Sector 79 Gurgaon, Gurgaon, Haryana",4,East,NaN,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","Individual bar plus ground floor room , two si...","['1 Water Purifier', '1 Fan', '1 Fridge', '1 D...","['Intercom Facility', 'Lift(s)', 'High Ceiling...","['Environment4 out of 5', 'Safety4 out of 5', ...",1400.0
4,3 BHK Flat in Sector 30 Gurgaon,flat,afnhb jalvayu vihar,1.3,10000.0,1300.0,Super Built up area 1500(139.35 sq.m.)Carpet a...,3,3,2,...,"Sector 30 Gurgaon, Gurgaon, Haryana",2,North-East,10+ Year Old,"['Huda city centre metro station', 'Axis bank ...",Property is fully renovated with all extention...,[],"['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Green Area4.5 out of 5', 'Construction4 out ...",1300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3021,3 BHK Flat in Sector-2 Sohna,flat,supertech hilltown,Not Avaliable,NaN,NaN,Built Up area: 1720 (159.79 sq.m.),3,3,3,...,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN,NaN
3022,2 BHK Flat in Sector 95A Gurgaon,flat,the roselia 2,Not Avaliable,NaN,NaN,Carpet area: 593 (55.09 sq.m.),2,2,2,...,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14,NA,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ...",NaN
3024,3 BHK Flat in Sector 104 Gurgaon,flat,godrej summit,Not Avaliable,NaN,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3,3,3,...,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14,NA,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of...",NaN
3025,4 BHK Flat in Gwal Pahari,flat,krrish provence estate,Not Avaliable,NaN,NaN,Built Up area: 5800 (538.84 sq.m.),4,5,1,...,"Gwal Pahari, Gurgaon, Haryana",17,NA,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN,NaN
3026,4 BHK Flat in Sector 95 Gurgaon,flat,sidhartha ncr one phase,Not Avaliable,NaN,NaN,Super Built up area 2354(218.69 sq.m.),4,4,3+,...,"Sector 95 Gurgaon, Gurgaon, Haryana",0,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5...",NaN

In [88]:
df

,property_name,property_type,society,price,price per sq feet,area1,areaWithType,bedRoom,bathroom,balcony,...,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,area
0,4 BHK Flat in Sector 85 Gurgaon,flat,godrej air,2.5,1379.0,18129.079043,Carpet area: 18122 (1683.59 sq.m.),4,5,3+,...,"1601-A 2, Sector 85 Gurgaon, Gurgaon, Haryana",16,North-East,2024-03-01 00:00:00,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...",Godrej as a brand and very few densed society,"['4 Wardrobe', '1 Water Purifier', '4 Fan', '1...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment5 out of 5', 'Lifestyle5 out of 5...",18129.079043
1,3 BHK Flat in Sector 88A Gurgaon,flat,godrej icon,1.75,1384.0,12644.508671,Carpet area: 1175.11,3,3,3+,...,"Sector 88A Gurgaon, Gurgaon, Haryana",6,NA,0 to 1 Year Old,"['JMS Crosswalk', ""Saint Paul's School"", 'Indu...",Godrej icon is one of the most popular destina...,[],NaN,NaN,12644.508671
2,3 BHK Flat in Malibu Town,flat,malibu towne,2.4,10000.0,2400.0,Carpet area: 2400 (222.97 sq.m.),3,3,0,...,"Malibu Town, Gurgaon, Haryana",0,West,5 to 10 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",Residential apartment for sell.The property co...,"['1 Water Purifier', '3 Fan', '1 Exhaust Fan',...","['Maintenance Staff', 'Swimming Pool', 'Park']","['Environment5 out of 5', 'Safety5 out of 5', ...",2400.0
3,2 BHK Flat in Sector 79 Gurgaon,flat,m3m golfestate,1.4,10000.0,1400.0,Carpet area: 1400 (130.06 sq.m.),2,2,2,...,"Sector 79 Gurgaon, Gurgaon, Haryana",4,East,NaN,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","Individual bar plus ground floor room , two si...","['1 Water Purifier', '1 Fan', '1 Fridge', '1 D...","['Intercom Facility', 'Lift(s)', 'High Ceiling...","['Environment4 out of 5', 'Safety4 out of 5', ...",1400.0
4,3 BHK Flat in Sector 30 Gurgaon,flat,afnhb jalvayu vihar,1.3,10000.0,1300.0,Super Built up area 1500(139.35 sq.m.)Carpet a...,3,3,2,...,"Sector 30 Gurgaon, Gurgaon, Haryana",2,North-East,10+ Year Old,"['Huda city centre metro station', 'Axis bank ...",Property is fully renovated with all extention...,[],"['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Green Area4.5 out of 5', 'Construction4 out ...",1300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3021,3 BHK Flat in Sector-2 Sohna,flat,supertech hilltown,Not Avaliable,NaN,NaN,Built Up area: 1720 (159.79 sq.m.),3,3,3,...,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN,NaN
3022,2 BHK Flat in Sector 95A Gurgaon,flat,the roselia 2,Not Avaliable,NaN,NaN,Carpet area: 593 (55.09 sq.m.),2,2,2,...,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14,NA,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ...",NaN
3024,3 BHK Flat in Sector 104 Gurgaon,flat,godrej summit,Not Avaliable,NaN,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3,3,3,...,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14,NA,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of...",NaN
3025,4 BHK Flat in Gwal Pahari,flat,krrish provence estate,Not Avaliable,NaN,NaN,Built Up area: 5800 (538.84 sq.m.),4,5,1,...,"Gwal Pahari, Gurgaon, Haryana",17,NA,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN,NaN
3026,4 BHK Flat in Sector 95 Gurgaon,flat,sidhartha ncr one phase,Not Avaliable,NaN,NaN,Super Built up area 2354(218.69 sq.m.),4,4,3+,...,"Sector 95 Gurgaon, Gurgaon, Haryana",0,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5...",NaN